//@version=5
indicator("EMA en Diario en Gráfico H4", overlay=true)

// Configuración de la EMA
emaLength = 54
src = close

// Obtener valores diarios de la EMA
dailyEMA = request.security(syminfo.tickerid, "D", ta.ema(src, emaLength))

// Convertir valores diarios al marco de tiempo H4
h4EMA = request.security(syminfo.tickerid, "240", dailyEMA)

// Configuración de las Bollinger Bands
length = input.int(20, minval=1)
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(close, length)
dev = mult * ta.stdev(close, length)
upper = basis + dev
lower = basis - dev

// Plot de las Bollinger Bands en el gráfico H4
p1 = plot(upper, "Upper", color=color.blue)
p2 = plot(lower, "Lower", color=color.blue)
fill(p1, p2, color=color.rgb(33, 150, 243, 95), title="Background")
// Plot de la EMA en el gráfico H4 con colores condicionales
emaColor = h4EMA > upper ? color.red : h4EMA < lower ? color.green : color.purple
plot(h4EMA, title="EMA Diario", color=emaColor, linewidth=2)
