strategy("Bollinger Bands Strategy", overlay=true)
// Bollinger bands
source = close
length = input.int(20, minval=1)
mult = input.float(2.0, minval=0.001, maxval=50)
basis = ta.sma(source, length)
dev = mult * ta.stdev(source, length)
upper = basis + dev
lower = basis - dev
buyEntry = ta.crossover(source, lower)
sellEntry = ta.crossunder(source, upper)

// Configuración de la EMA
emaLength = 54
src = close

// Obtener valores diarios de la EMA
dailyEMA = request.security(syminfo.tickerid, "D", ta.ema(src, emaLength))

// Convertir valores diarios al marco de tiempo H4
h4EMA = request.security(syminfo.tickerid, "240", dailyEMA)




if (ta.crossover(source, lower))
	strategy.entry("BBandLE", strategy.long, stop=lower, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandLE")
else
	strategy.cancel(id="BBandLE")
if (ta.crossunder(source, upper))
	strategy.entry("BBandSE", strategy.short, stop=upper, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandSE")
else
	strategy.cancel(id="BBandSE")