//@version=5
strategy("Bollinger Bands Strategy with EMA", overlay=true)
strategy.risk.max_drawdown(2, strategy.percent_of_equity)
// **
// * EMA
// **
ema_periods = input.int(54, minval=1, maxval=200)
ema_data = input.string(defval = "D", title = "ema_dataframe", options = ["D", "240", "60", "15", "5"], tooltip = "dataframe", display = display.all)
exponential_moving_average = request.security(syminfo.tickerid, ema_data, ta.ema(close, ema_periods))
// **
// * END OF EMA
// **

// **
// * BOLLINGER BANDS
// **
bollinger_length = input.int(20, minval=1)
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(close, bollinger_length)
dev = mult * ta.stdev(close, bollinger_length)
upper_band = basis + dev
lower_band = basis - dev
// **
// * END OF BOLLINGER BANDS
// **

// **
// * ATR Stop losss
// **
length = input.int(title='Length', defval=14, minval=1)
smoothing = input.string(title='Smoothing', defval='RMA', options=['RMA', 'SMA', 'EMA', 'WMA'])
m = input(1.5, 'Multiplier')
src1 = input(high)
src2 = input(low)
pline = input(true, 'Show Price Lines')
col1 = input(color.blue, 'ATR Text Color')
col2 = input.color(color.teal, 'Low Text Color', inline='1')
col3 = input.color(color.red, 'High Text Color', inline='2')
collong = input.color(color.teal, 'Low Line Color', inline='1')
colshort = input.color(color.red, 'High Line Color', inline='2')
ma_function(source, length) =>
    if smoothing == 'RMA'
        ta.rma(source, length)
    else
        if smoothing == 'SMA'
            ta.sma(source, length)
        else
            if smoothing == 'EMA'
                ta.ema(source, length)
            else
                ta.wma(source, length)
a = ma_function(ta.tr(true), length) * m
x = ma_function(ta.tr(true), length) * m + src1
x2 = src2 - ma_function(ta.tr(true), length) * m
p1_atr = plot(x, title='ATR Short Stop Loss', color=colshort, trackprice=pline ? true : false, transp=20)
p2_atr = plot(x2, title='ATR Long Stop Loss', color=collong, trackprice=pline ? true : false, transp=20)
var table Table = table.new(position.bottom_center, 3, 1, border_width=3)
f_fillCell(_table, _column, _row, _value, _timeframe) =>
    _cellText = _timeframe + str.tostring(_value, '#.#')
    table.cell(_table, _column, _row, _cellText, text_color=col1)
    table.cell_set_text_color(Table, 1, 0, color.new(col3, transp=0))
    table.cell_set_text_color(Table, 2, 0, color.new(col2, transp=0))
if barstate.islast
    f_fillCell(Table, 0, 0, a, 'ATR: ')
    f_fillCell(Table, 1, 0, x, 'H: ')
    f_fillCell(Table, 2, 0, x2, 'L: ')
// **
// * END OF ATR Stop losss
// **

// Bollinger Bands plot on the H4 chart
p1 = plot(upper_band, "Upper", color=color.blue)
plot(basis, "Basis", color=color.orange)
p2 = plot(lower_band, "Lower", color=color.blue)
fill(p1, p2, color=color.rgb(33, 150, 243, 95), title="Background")
// EMA plot on the H4 chart with varying colors
ema_color = exponential_moving_average > upper_band ? color.red : exponential_moving_average < lower_band ? color.green : color.purple
plot(exponential_moving_average, title="Daily EMA", color=ema_color, linewidth=2)

/// Conditions to go long
buy_condition = low <= lower_band and exponential_moving_average < lower_band

// Conditions to go short
sell_condition = high >= upper_band and exponential_moving_average > upper_band

// Conditions to close the long position
close_buy_condition = close >= basis

// Conditions to close the short position
close_sell_condition = close <= basis

float stop_loss_long = na
float stop_loss_short = na
// Go long
if (buy_condition)
    stop_loss_long := close - x2
    strategy.entry("buy_entry", strategy.long, comment="buy_entry", stop=stop_loss_long)
// Go short
if (sell_condition)
    stop_loss_short := close + x
    strategy.entry("sell_entry", strategy.short, comment="sell_entry", stop=stop_loss_short)
// Close the long position if the closure condition is met
if (close_buy_condition)
    strategy.close("buy_entry")
// Close the short position if the closure condition is met
if (close_sell_condition)
    strategy.close("sell_entry")



// THIS STOP LOSS DOESNT WORK AS EXPECTED

// Add stop-loss for long positions
if (close <= stop_loss_long)
    stop_loss_long := na
    strategy.close("buy_entry", comment="STOP LOSS")
// Add stop-loss for short positions
if (close >= stop_loss_short)
    stop_loss_short := na
    strategy.close("sell_entry", comment="STOP LOSS")